# We use Docker → we need sudo.
sudo: required

services:
  - docker

script:
  - bash ci/build.sh

deploy:
  - provider: script
    script: PUBLISH=true bash ci/build.sh
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false
