# We use Docker → we need sudo.
sudo: required

services:
  - docker

script:
  - ci/build.sh

deploy:
  - provider: script
    script: PUBLISH=true ci/build.sh
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false

before_cache:
  - rm -f  "$HOME"/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
